/**:
  ros__parameters:
    init:
      output: "compressed"
    pre_stream:
      resolution: "4K"
      fps_format: 30
    runtime:
      fps: 23
      exposure_mode: 1
      exposure_time_us: 1000
      jpeg_quality: 205
      ehdr_exposure_max_number: 3
